GET http://localhost:5000/categories

###
POST http://localhost:5000/categories
content-type: application/json

{
    "name":"Car",
    "slug": "car",
    "imgUrl" : ""
}

###

PUT  http://localhost:5000/categories/1
Content-Type: application/json

{
    "name": "lolokavj",
    "slug": "aijhgiau",
    "imgUrl": "njni"
}

###

DELETE http://localhost:5000/categories/2

